### ISSUE TITLE
pymysql.err.InternalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

### ISSUE THREAD

**Issue by wencan** [aio-libs/aiomysql#165]
source code:

    import asyncio
    from aiomysql import create_pool

    loop = asyncio.get_event_loop()

    async def go():
        async with create_pool(host='localhost', port=3306,
                               user='root', password='123456',
                               db='test', autocommit=True, loop=loop) as pool:
            async with pool.get() as conn:
                for i in range(1000):
                    async with conn.cursor() as cur:
                        await cur.execute("UPDATE number SET idnumber = idnumber - 1 WHERE name = 'test';")
                        await cur.fetchone()

    loop.run_until_complete(go())

traceback:  

    Traceback (most recent call last):
      File "testdb.py", line 24, in <module>
        loop.run_until_complete(go())
      File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
        return future.result()
      File "testdb.py", line 20, in go
        await cur.execute("UPDATE number SET idnumber = idnumber - 1 WHERE name = 'test';")
      File "/usr/local/lib/python3.6/site-packages/aiomysql/cursors.py", line 239, in execute
        yield from self._query(query)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/cursors.py", line 460, in _query
        yield from conn.query(q)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 398, in query
        yield from self._read_query_result(unbuffered=unbuffered)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 582, in _read_query_result
        yield from result.read()
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 835, in read
        first_packet = yield from self.connection._read_packet()
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 552, in _read_packet
        packet.check_error()
      File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
        err.raise_mysql_exception(self._data)
      File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
        raise errorclass(errno, errval)
    pymysql.err.InternalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

Triggering conditions:
The number of concurrent processes is 4

**Comment by jettify** [comment]
Hi, looks like issue mysql related, not sure what aiomysql can do here, see more information:
https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks.html

**Comment by jettify** [comment]
Looks like not aiomysql issue, feel free to reopen with more information

**Comment by houyingkun** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by terrycain** [comment]
It looks mysql related, so perhaps either a bug fix in  mysql or perhaps a newer mysql server version?
