### ISSUE TITLE
RuntimeError: readexactly() called while another coroutine is already waiting for incoming data

### ISSUE THREAD

**Issue by denglj** [aio-libs/aiomysql#179]
Hello, friends:
I encountered some trouble while trying to use the mysql connection concurrently. Here is the error message:
```
Traceback (most recent call last):
  File "test_aiomysql.py", line 63, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/Users/ju/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "test_aiomysql.py", line 53, in create_foo
    foo = await Foo.create_by_id(_id)
  File "test_aiomysql.py", line 39, in create_by_id
    await cur.execute(sql)
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/cursors.py", line 239, in execute
    yield from self._query(query)
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/cursors.py", line 460, in _query
    yield from conn.query(q)
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/connection.py", line 398, in query
    yield from self._read_query_result(unbuffered=unbuffered)
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/connection.py", line 582, in _read_query_result
    yield from result.read()
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/connection.py", line 835, in read
    first_packet = yield from self.connection._read_packet()
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/connection.py", line 520, in _read_packet
    packet_header = yield from self._read_bytes(4)
  File "/Users/ju/.pyenv/versions/apollo/lib/python3.6/site-packages/aiomysql/connection.py", line 558, in _read_bytes
    data = yield from self._reader.readexactly(num_bytes)
  File "/Users/ju/.pyenv/versions/3.6.1/lib/python3.6/asyncio/streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/Users/ju/.pyenv/versions/3.6.1/lib/python3.6/asyncio/streams.py", line 446, in _wait_for_data
    'already waiting for incoming data' % func_name)
RuntimeError: readexactly() called while another coroutine is already waiting for incoming data
```

### Environment:
* **MySQL Server OS**: CentOS Linux release 7.1.1503 (Core)
* **MySQL Version**: mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
* **Local OS:** Mac OS X, 10.12.4
* **Python Version**: 3.6.1
* **aiomysql**: 0.0.9
* **PyMySQL**: 0.7.11

### My Code:
```python
import asyncio
import aiomysql

loop = asyncio.get_event_loop()

dbcfg = {
    'charset': 'utf8',
    'db': 'db_name',
    'host': '10.60.88.250',
    'username': 'testuser',
    'password': 'PasSWorD',
    'port': 3306
}

async def _make_connection():
    return await aiomysql.connect(host=dbcfg['host'], port=int(dbcfg['port']),
                                  user=dbcfg['username'],
                                  password=dbcfg['password'],
                                  db=dbcfg['db'], charset='utf8mb4',
                                  cursorclass=aiomysql.DictCursor)

# I want get a connection when the project initialization and reuse it anywhere.
global_conn = loop.run_until_complete(_make_connection())

class Foo:

    # all of the Foo's object share one connection object. 
    _conn = global_conn

    def __init__(self, *args, **kwargs):
        pass

    @classmethod
    async def create_by_id(cls, _id):
        async with cls._conn.cursor() as cur:
            sql = ("select * from spider_source_feed where "
                   "`url_md5`='{linkmd5}'").format(linkmd5=_id)
            await cur.execute(sql)
            result = await cur.fetchone()
            return cls(**result)


async def create_foo(_id):
    return await Foo.create_by_id(_id)

if __name__ == '__main__':
    ids = ['id1', 'id2', 'id3']
    tasks = [create_foo(i) for i in ids]

    loop = asyncio.get_event_loop()
    # create Foo's object concurrently
    loop.run_until_complete(asyncio.gather(*tasks))
```
execute the above code, can reproduce the error.

if we just for no error, I found two ways to fix it:
* don't create foo obejct concurrently
```python
loop.run_until_complete(create_foo('id1'))
```
* create mysql connection every time in Foo

### But
I really need create multi Foo object at once. make mysql connection anywhere anytime is OK？or how can I fix this problem?

Thanks.

**Comment by jettify** [comment]
Connection can not be used concurrently, use pool of connection instead.

**Comment by jettify** [comment]
See example here https://github.com/aio-libs/aiomysql/blob/master/examples/example_pool.py

**Comment by dondublon** [comment]
What if I try running several queries simultaneously?
