### ISSUE TITLE
sqlalchemy 1.2.0b3 has not attribute 'dbapi_type_map'

### ISSUE THREAD

**Issue by DeoLeung** [aio-libs/aiomysql#228]
```sh
Traceback (most recent call last):
File "/xxx/.virtualenvs/risk/lib/python3.6/site-packages/aiomysql/utils.py", line 66, in __await__
    resp = yield from self._coro
  File "/xxx/.virtualenvs/risk/lib/python3.6/site-packages/aiomysql/sa/connection.py", line 113, in _execute
    ret = yield from create_result_proxy(self, cursor, self._dialect)
  File "/xxx/.virtualenvs/risk/lib/python3.6/site-packages/aiomysql/sa/result.py", line 17, in create_result_proxy
    yield from result_proxy._prepare()
  File "/xxx/.virtualenvs/risk/lib/python3.6/site-packages/aiomysql/sa/result.py", line 237, in _prepare
    self._metadata = ResultMetaData(self, cursor.description)
  File "/xxx/.virtualenvs/risk/lib/python3.6/site-packages/aiomysql/sa/result.py", line 107, in __init__
    typemap = dialect.dbapi_type_map
AttributeError: 'MySQLDialect_pymysql' object has no attribute 'dbapi_type_map'
```
it looks like `sqlalchemy==1.2.0b3` breaks something

**Comment by jettify** [comment]
I will take a look related aiopg issue https://github.com/aio-libs/aiopg/pull/412/files

**Comment by jettify** [comment]
Fixed, new version already on PyPI https://pypi.python.org/pypi/aiomysql/0.0.12
