### ISSUE TITLE
"Can't connect to MySQL server on 'localhost'"

### ISSUE THREAD

**Issue by rekt4lifecs** [aio-libs/aiomysql#267]
randomly just happened. Works fine on windows locally but on a new ubuntu server it justs gives out
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "bot.py", line 89, in on_message
    db=config.db.database)
  File "/usr/local/lib/python3.6/dist-packages/aiomysql/utils.py", line 75, in __await__
    resp = yield from self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiomysql/connection.py", line 78, in _connect
    yield from conn._connect()
  File "/usr/local/lib/python3.6/dist-packages/aiomysql/connection.py", line 496, in _connect
    self._host) from e
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost'")
```
password, host, user are all correct. Using aiomysql 0.0.12 and mysql 5.7.21

**Comment by Sultan91** [comment]
Same thing for me

**Comment by mesher23** [comment]
try     
conn = await aiomysql.connect(host='127.0.0.1', port=3306,
                                       user='some_user', password='some_pass', db='mysql',
                                       loop=loop)

**Comment by SuperTommy007** [comment]
on terminal can connect with 'localhost', but code can't....so weird
