### ISSUE TITLE
Cannot connect to mysql 8

### ISSUE THREAD

**Issue by and800** [aio-libs/aiomysql#297]
Mysql8 connection attempt fails with error "Access denied for user (using password: NO)", but the password is among args.

I believe this can be related to new mysql authentication method (see https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded).

Test code:
```python
import asyncio
import aiomysql

args = {
    'port': 3306,
    'user': 'test',
    'password': 'test',
    'db': 'test',
}

async def connect():
    # MYSQL_VERSION=5.7.22-1debian9
    await aiomysql.connect(host='mysql5', **args)
    print('mysql5 works\n')

    # MYSQL_VERSION=8.0.11-1debian9
    await aiomysql.connect(host='mysql8', **args)
    print('mysql8 works\n')

asyncio.get_event_loop().run_until_complete(connect())
```

Log:
```
mysql5 works

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 464, in _connect
    await self._request_authentication()
  File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 719, in _request_authentication
    auth_packet = await self._read_packet()
  File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 554, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'test'@'172.18.0.3' (using password: NO)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(connect())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "main.py", line 17, in connect
    await aiomysql.connect(host='mysql8', **args)
  File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 76, in _connect
    await conn._connect()
  File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 484, in _connect
    self._host) from e
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mysql8'")

```

**Comment by and800** [comment]
Mysql has changed its default auth plugin to `caching_sha2_password` since version 8, and aiomysql doesn't know about this plugin.

People from Pymysql are currently working on the patch (https://github.com/PyMySQL/PyMySQL/pull/682). That patch should be copypasted into aiomysql code, when it's ready

**Comment by terrycain** [comment]
Am planning to add this after #309

**Comment by terrycain** [comment]
Well it was simpler than I expected. I have a "working for me" copy on my fork here - https://github.com/terrycain/aiomysql/tree/sha256 Waiting on #309 but then it just needs the test suit to be ran against MySQL8

**Comment by LemonPi** [comment]
Waiting for this update. Currently there's no way to connect to a MySQL 8 DB without changing it to use native passwords right? 

PyMySQL 9 is needed to support the new sha256 passwords and an update to aiomysql is needed to support the auth move in PyMySQL.

**Comment by terrycain** [comment]
@LemonPi Yep, and even on ubuntu 18.04 the mariadb client install doesnt come with the sha256 libraries for me so I had to run mysql client in a container just connect and test :laughing:
