### ISSUE TITLE
Fix async iterator protocol in aiomysql.utils._SAConnectionContextManager

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiomysql#410]
`__aiter__()` should be a non-coroutine method returning an instance having `__anext__()` coroutine method.

```python-traceback
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
```

Example: https://github.com/aio-libs/aiopg/commit/ef1cabeeb7023841184f23197298215d1d45209d#diff-222246bbd6dde09cb363ee2c57a67887R72

**Comment by ruiboma** [comment]
Did the mistake arise in this way?
async def go():
	engine = await create_engine(user="xxx", password="mrb", host='localhost', db="xxx")
	conn = await engine._acquire()
	res = conn.execute("select * from xxx.user")
	async for row in res:
		print(row.id)

**Comment by webknjaz** [comment]
I don't remember but probably yes.

**Comment by ruiboma** [comment]
I find that this error no longer occurs, and _aiter_ of _SAConnectionContextManager returns the ResultProxy object. ResultProxy objects already have a complete iterative protocol.

**Comment by jaggerwang** [comment]
Same problem, still there!

**Comment by MateuszCzubak** [comment]
@jaggerwang Do you mind providing an example to reproduce the bug? I fail to find one since, as mentioned by @ruiboma, `_SAConnectionContextManager` returns the `ResultProxy`.

**Comment by willbuckner** [comment]
I'm seeing this here on Python 3.8:

```python
from aiomysql import sa

app = Sanic('test app')

@app.listener('before_server_start')
async def register_db(app, loop):
    connection_params = parse_db_uri(app.config['MYSQL_URI'])

    app.pool = await sa.create_engine(**connection_params)

    async with app.pool.acquire() as connection:
        result = await connection.execute('SELECT 1')
        async for row in result.fetchall():
            print(row)
```

```
Traceback (most recent call last):
  File "./main.py", line 44, in <module>
    app.run(host='127.0.0.1', port=8000, access_log=True, debug=True)
  File "/usr/local/var/pyenv/versions/3.8.6/lib/python3.8/site-packages/sanic/app.py", line 1130, in run
    serve(**server_settings)
  File "/usr/local/var/pyenv/versions/3.8.6/lib/python3.8/site-packages/sanic/server.py", line 888, in serve
    trigger_events(before_start, loop)
  File "/usr/local/var/pyenv/versions/3.8.6/lib/python3.8/site-packages/sanic/server.py", line 696, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "./main.py", line 33, in register_db
    async for row in result.fetchall():
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

**Comment by fury185** [comment]
Same problem, still there
python 3.8.5
