### ISSUE TITLE
when minsize reach can't acquire a new connection ,it return a exit conn

### ISSUE THREAD

**Issue by futianshi1314** [aio-libs/aiomysql#413]
code as folows:---------

```python
import aiomysql
import asyncio
from aiomysql.cursors import DictCursor

class MySQL_Pool(object):

    async def init_pool(self):
        self.pool = await aiomysql.create_pool(host='10.16.xx.xx',
                                               port=3306, minsize=5, maxsize=50, user='k8sadmin',
                                               password='123456', db='kubernetes_backend')
        return self.pool

class MySQL_Conn(object):

    def __init__(self, pool):
        self.pool = pool

    async def get_conn(self):
        async with self.pool.acquire() as self.conn:
            print(self.conn)
            pass

    def close_conn(self):
        self.pool.release(self.conn)

    async def execute(self, sql):
        async with self.conn.cursor(DictCursor) as cur:
            await cur.execute(sql)
            r = await cur.fetchall()
            await self.conn.commit()
            print(r)

async def query_db(pool):
    mysql = MySQL_Conn(pool)
    await mysql.get_conn()
    k = await mysql.execute("select name from tb_deployment where id=60")
    #mysql.close_conn()

async def main():
    task_lst = []
    for i in range(6):
        task_lst.append(
            asyncio.create_task(query_db(pool))
        )
    for i in task_lst:
        await i

mysql_loop = asyncio.get_event_loop()
pool = mysql_loop.run_until_complete(MySQL_Pool().init_pool())
mysql_loop.run_until_complete(main())
```
-------------

I run less than 5 coroutine to select ,it has no problem, when I run more than 5 coroutine ,pool.acquire() will get an existing conn,not new connection, I print the conn, such i run this with 6 coroutine ,as  result as follows:

---------------------
```python
<aiomysql.connection.Connection object at 0x7fde099b5a90>
<aiomysql.connection.Connection object at 0x7fde099b5f60>
<aiomysql.connection.Connection object at 0x7fde099d1240>
<aiomysql.connection.Connection object at 0x7fde099d1470>
<aiomysql.connection.Connection object at 0x7fde099d16a0>
<aiomysql.connection.Connection object at 0x7fde099b5a90>
Traceback (most recent call last):
  File "aiomysqltest.py", line 48, in <module>
    mysql_loop.run_until_complete(main())
  File "/usr/local/Python-3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "aiomysqltest.py", line 44, in main
    await i
  File "aiomysqltest.py", line 35, in query_db
    k = await mysql.execute("select name from tb_deployment where id=60")
  File "aiomysqltest.py", line 29, in execute
    await self.conn.commit()
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 353, in commit
    await self._read_ok_packet()
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 333, in _read_ok_packet
    raise OperationalError(2014, "Command Out of Sync")
pymysql.err.OperationalError: (2014, 'Command Out of Sync')
Task exception was never retrieved
future: <Task finished coro=<query_db() done, defined at aiomysqltest.py:32> exception=RuntimeError('readexactly() called while another coroutine is already waiting for incoming data')>
Traceback (most recent call last):
  File "aiomysqltest.py", line 35, in query_db
    k = await mysql.execute("select name from tb_deployment where id=60")
  File "aiomysqltest.py", line 27, in execute
    await cur.execute(sql)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 561, in _read_packet
    packet_header = await self._read_bytes(4)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/connection.py", line 598, in _read_bytes
    data = await self._reader.readexactly(num_bytes)
  File "/usr/local/Python-3.7.3/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/Python-3.7.3/lib/python3.7/asyncio/streams.py", line 460, in _wait_for_data
    f'{func_name}() called while another coroutine is '
RuntimeError: readexactly() called while another coroutine is already waiting for incoming data
```
------------------
you can see the printed conn has 6,but one is same as the other:<aiomysql.connection.Connection object at 0x7fde099b5a90>

Am I using the wrong method?
and how can i release the conn, when i use pool.release(conn),Remove the comment(mysql_close_conn()), it will exception:

------------------------
```python
Traceback (most recent call last):
  File "aiomysqltest.py", line 49, in <module>
    mysql_loop.run_until_complete(main())
  File "/usr/local/Python-3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "aiomysqltest.py", line 45, in main
    await i
  File "aiomysqltest.py", line 36, in query_db
    mysql.close_conn()
  File "aiomysqltest.py", line 23, in close_conn
    self.pool.release(self.conn)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/pool.py", line 204, in release
    assert conn in self._used, (conn, self._used)
AssertionError: (<aiomysql.connection.Connection object at 0x7f30c3745eb8>, set())
Task exception was never retrieved
future: <Task finished coro=<query_db() done, defined at aiomysqltest.py:32> exception=AssertionError((<aiomysql.connection.Connection object at 0x7f30bf5266d8>, set()))>
Traceback (most recent call last):
  File "aiomysqltest.py", line 36, in query_db
    mysql.close_conn()
  File "aiomysqltest.py", line 23, in close_conn
    self.pool.release(self.conn)
  File "/usr/local/Python-3.7.3/lib/python3.7/site-packages/aiomysql/pool.py", line 204, in release
    assert conn in self._used, (conn, self._used)
AssertionError: (<aiomysql.connection.Connection object at 0x7f30bf5266d8>, set())
```
-----------------------------
this is not a problem, when the coroutine ended the conn will auto release
thanks

**Comment by asvetlov** [comment]
Sorry, the message is unreadable.
Please reformat it with backticks: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by futianshi1314** [comment]
> Sorry, the message is unreadable.
> Please reformat it with backticks: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

sorry, I've reedited it

**Comment by futianshi1314** [comment]
I have know why: 
async def get_conn(self):
        async with self.pool.acquire() as self.conn:
            print(self.conn)
            pass
async with self.pool.acquire() as self.conn    ==>   self.conn = self.pool.acquire()
close the issue

**Comment by futianshi1314** [comment]
no problem
