### ISSUE TITLE
Error cur = self.cursorclass(self, self._echo)

### ISSUE THREAD

**Issue by romariosar** [aio-libs/aiomysql#429]
I copied the first example

```

import asyncio
import aiomysql
import pymysql

async def test_example(loop):
    pool = await aiomysql.create_pool(host='127.0.0.1',
                                  user='usert',
                                  password='user',
                                  db='tes',
                                  charset='utf8mb4',
                                  cursorclass=pymysql.cursors.DictCursor,
                                  autocommit=True,
                                  loop=loop)
    async with pool.acquire() as conn:
        async with conn.cursor() as cur:
            await cur.execute("SELECT 42;")
            print(cur.description)
            (r,) = await cur.fetchone()
            assert r == 42
    pool.close()
    await pool.wait_closed()



loop = asyncio.get_event_loop()
loop.run_until_complete(test_example(loop))
```
and as a result I have an error

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    loop.run_until_complete(test_example(loop))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 15, in test_example
    async with conn.cursor() as cur:
  File "/usr/local/lib/python3.7/site-packages/aiomysql/connection.py", line 417, in cursor
    cur = self.cursorclass(self, self._echo)
TypeError: __init__() takes 2 positional arguments but 3 were given
```
how it fix?

**Comment by romariosar** [comment]
Solved, need to delete string:

`cursorclass=pymysql.cursors.DictCursor,`
