### ISSUE TITLE
`create_pool` can not work with `async/await` feature

### ISSUE THREAD

**Issue by lxneng** [aio-libs/aiomysql#49]
## test script

```py
import asyncio
import aiomysql


loop = asyncio.get_event_loop()


async def test_example():
        pool = await aiomysql.create_pool(host='127.0.0.1', port=3306,
                                               user='root', password='',
                                               db='mysql', loop=loop)
        with (await pool) as conn:
            cur = await conn.cursor()
            await cur.execute("SELECT 10")
            # print(cur.description)
            (r,) = await cur.fetchone()
            assert r == 10
        pool.close()
        await pool.wait_closed()

loop.run_until_complete(test_example())
```

## Error Traceback

```
Traceback (most recent call last):
  File "aiomysql_pool.py", line 21, in <module>
    loop.run_until_complete(test_example())
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "aiomysql_pool.py", line 12, in test_example
    with (await pool) as conn:
  File "/Users/Eric/Projects/Python/aiomysql/aiomysql/utils.py", line 121, in __enter__
    assert self._conn
AssertionError
...
```

**Comment by jettify** [comment]
Hi @lxneng!
Please use `async with` instead of regular `with`
```python
async def test_example():
    pool = await aiomysql.create_pool(host='127.0.0.1', port=3306, ...)
    async with pool:
        cur = await conn.cursor()
        await cur.execute("SELECT 10")
```

**Comment by lxneng** [comment]
Ok, Thanks! :+1:

**Comment by jettify** [comment]
Sorry, I posted wrong example, here is proper one:
```python
import asyncio
from aiomysql import create_pool


loop = asyncio.get_event_loop()

async def go():
    async with create_pool(host='127.0.0.1', port=3306,
                           user='root', password='',
                           db='mysql', loop=loop) as pool:
        async with pool.get() as conn:
            async with conn.cursor() as cur:
                await cur.execute("SELECT 42;")
                value = await cur.fetchone()
                print(value)

loop.run_until_complete(go())
```

my initial example works too but you need acquire connection explicitly:
```python
 async with pool:
    conn = await pool.acquire()

```

**Comment by lxneng** [comment]
Got it, Thanks a lot. :+1:
