### ISSUE TITLE
Impossible to install via PyPI

### ISSUE THREAD

**Issue by GMLudo** [aio-libs/aiomysql#5]
Hi,

I can't install aiomysql via PyPI with pip.
It's ok via Git repository.
You should add a Manifest.in file to include RST files.

Log message:
```
(pyvenv) lg@steroids:~/tmp$ pip install aiomysql
Downloading/unpacking aiomysql
  Downloading aiomysql-0.0.1.tar.gz (44kB): 44kB downloaded
  Running setup.py (path:/home/lg/tmp/pyvenv/build/aiomysql/setup.py) egg_info for package aiomysql
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/lg/tmp/pyvenv/build/aiomysql/setup.py", line 54, in <module>
        long_description='\n\n'.join((read('README.rst'), read('CHANGES.rst'))),
      File "/home/lg/tmp/pyvenv/build/aiomysql/setup.py", line 20, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/tmp/pyvenv/build/aiomysql/CHANGES.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/lg/tmp/pyvenv/build/aiomysql/setup.py", line 54, in <module>

    long_description='\n\n'.join((read('README.rst'), read('CHANGES.rst'))),

  File "/home/lg/tmp/pyvenv/build/aiomysql/setup.py", line 20, in read

    return open(os.path.join(os.path.dirname(__file__), f)).read().strip()

FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/tmp/pyvenv/build/aiomysql/CHANGES.rst'
```

**Comment by jettify** [comment]
Fixed. Thank you!

**Comment by GMLudo** [comment]
Thank you, it works as excepted.
