### ISSUE TITLE
在fastapi中使用aiomysql会不定时报错

### ISSUE THREAD

**Issue by xujiang1** [aio-libs/aiomysql#599]
```
 Traceback (most recent call last):
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 598, in _read_bytes
    data = await self._reader.readexactly(num_bytes)
  File "D:\Program Files\Python38\lib\asyncio\streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 503, in _connect
    await self._request_authentication()
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 785, in _request_authentication
    auth_packet = await self._read_packet()
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 561, in _read_packet
    packet_header = await self._read_bytes(4)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 601, in _read_bytes
    raise OperationalError(2013, msg) from e
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\re_common\baselibrary\utils\core\mdeprecated.py", line 128, in wrapper
    return await func(*args, **kwargs)
  File "D:\fastapi_cjserver\apps\crawler_platform\qk_platform\journal_issue_down.py", line 210, in get_sql
    row = await CoreSqlMixin.get_issuelist(self.pm.task_name, self.pm.task_tag,
  File "D:\fastapi_cjserver\apps\crawler_platform\core_platform\core_sql.py", line 104, in get_issuelist
    async with pool.acquire() as conn:
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\utils.py", line 98, in __aenter__
    self._conn = await self._coro
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\pool.py", line 135, in _acquire
    await self._fill_free_pool(True)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\pool.py", line 180, in _fill_free_pool
    conn = await connect(echo=self._echo, loop=self._loop,
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 75, in _connect
    await conn._connect()
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\aiomysql\connection.py", line 521, in _connect
    raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.31.27'")

```

提示我无法连接数据库，但大多数情况下是正确的，只是偶尔会出现这个错误

**Comment by TnTomato** [comment]
Hi,
You should check your project's and mysql's configuration about connections.

**Comment by xujiang1** [comment]
发现错误来源于 mysql的连接数满了，不是来自配置错误

**Comment by Nothing4You** [comment]
Hi,

unfortunately I cannot help you based on the provided information.

In case of trying to request more connections from the pool than the pool's `maxsize` it will "block" until a connection is returned.
In case of trying to open more connections to the MySQL server (tested via `set global max_connections=2;` on MySQL 8.0) this will raise a `pymysql.err.OperationalError: (1040, 'Too many connections')`.

If you have a way to reproduce this please raise a new issue in English and with reproduction details.
