### ISSUE TITLE
pymysql.err.InternalError: (2003, "Can't connect to remote MySQL server for client connected to '0.0.0.0:3306'

### ISSUE THREAD

**Issue by verilogtester** [aio-libs/aiomysql#604]
This code works perfectly fine for 10-11 hours, and after that suddenly see the db connection error. full stacktrace is pasted below

Python code where the issue(stack trace is shown below) is shown:

```
            con = await aiomysql.connect(user=self.user, password=self.pwd, host=self.host, 
                                         db=database, connect_timeout=connection_timeout)
```

I am not specifying port here. do I need to specify port as well, to get rid of the issue shown below in the code ? Or the issue is something else here ? 

Environment:
=================
aiomysql        0.0.21
cryptography    3.4.7
mypy-extensions 0.4.3
PyMySQL         0.9.3
Python             3.8.8

Stack trace:
==================
```
[2021-08-03 05:55:02], DEBUG, begin to connect DB project_test., (abstract_config_manager:73)
[2021-08-03 05:55:02], ERROR, Database connection error: Traceback (most recent call last):
 File "/usr/local/dir//venv/lib/python3.8/site-packages/aiomysql/connection.py", line 502, in _connect
   await self._get_server_information()
 File "/usr/local/dir//venv/lib/python3.8/site-packages/aiomysql/connection.py", line 989, in _get_server_information
   packet = await self._read_packet()
 File "/usr/local/dir//venv/lib/python3.8/site-packages/aiomysql/connection.py", line 593, in _read_packet
   packet.check_error()
 File "/usr/local/dir//venv/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
   err.raise_mysql_exception(self._data)
 File "/usr/local/dir//venv/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
   raise errorclass(errno, errval)
pymysql.err.InternalError: (2003, "Can't connect to remote MySQL server for client connected to '0.0.0.0:3306'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/usr/local/dir//src/config/abstract_config_manager.py", line 74, in __execute
   con = await aiomysql.connect(user=self.user, password=self.pwd, host=self.host,
 File "/usr/local/dir//venv/lib/python3.8/site-packages/aiomysql/connection.py", line 75, in _connect
   await conn._connect()
 File "/usr/local/dir//venv/lib/python3.8/site-packages/aiomysql/connection.py", line 521, in _connect
   raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'my-server-router.my.company.com'")
, (abstract_config_manager:91)
[2021-08-03 05:55:02], ERROR, Exception: TypeError("'NoneType' object is not subscriptable"), 
```

**Comment by verilogtester** [comment]
Hi Looks like I am able to identify and fix this issue at my end. TypeError in the last shows the location where fix was needed. close this ticket.
