### ISSUE TITLE
Connection of any kind Issues (1043 Bad Handshake)

### ISSUE THREAD

**Issue by trivigy** [aio-libs/aiomysql#85]
Trying to connect to the database and getting a really weird error. Tried doing this without aiomysql but rather directly with PyMySQL and the connection worked fine. Would greatly appreciate some help.

Environment:
Mysql: 5.7.12
python: 3.5.1+
PyMySQL: 0.7.4
aiomysql: 0.0.7

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/connection.py", line 447, in _connect
    yield from self._request_authentication()
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/connection.py", line 615, in _request_authentication
    auth_packet = yield from self._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/connection.py", line 500, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
pymysql.err.InternalError: (1043, 'Bad handshake')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 22, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 373, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "<input>", line 11, in test_example
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/utils.py", line 57, in __await__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/pool.py", line 28, in _create_pool
    yield from pool._fill_free_pool(False)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/pool.py", line 163, in _fill_free_pool
    **self._conn_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/utils.py", line 52, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/connection.py", line 76, in _connect
    yield from conn._connect()
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/connection.py", line 467, in _connect
    self._host) from e
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'XXX.XXX.XXX.XXX'")
```

**Comment by trivigy** [comment]
Alright so it seems that the python 3.5 async/await style is not working. The old style seems to work fine. When I'll have some more time I'll try investigating a little further but looking through some minor dynamic analysis of wireshark it seems that the authentication packet is malformed. I bet because of the await stuff something doesn't get appended somewhere.

**Comment by jettify** [comment]
Hi, looks like problem because newer version of pymysql, try to downgrade to `PyMySQL<=0.6.7`. Will upgrade aiomysql soon.

**Comment by trivigy** [comment]
Yep. Totally right man. Thanks a lot. Feel free to close the issue.

**Comment by xiaoyue2019** [comment]
thanks

**Comment by xiaoyue2019** [comment]
> 
> 
> 嗨,看起来像问题,因为新版本的pymysql,下调 `PyMySQL < = 0.6.7 `。 很快就会升级aiomysql。

thanks
