### ISSUE TITLE
Allow pulling down MetaData via reflection

### ISSUE THREAD

**Issue by tkram01** [aio-libs/aiomysql#94]
Is there a way to pull down Table data with the aiomysql.sa API? When I try either of the following I get an error.

`meta = MetaData()`
`yield from meta.reflect(bind=engine)`

or 

`meta = MetaData()`
`Table('test_table', meta, autoload=True, autoload_with=engine)`

File "/anaconda/envs/asap/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/anaconda/envs/asap/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/anaconda/envs/asap/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Users/user/Documents/test/loader/loader_asyncio.py", line 39, in get_vrts
    yield from get_data(engine, vrt)
  File "/Users/user/Documents/test/loader/loader_asyncio.py", line 53, in get_data
    yield from _get_compound_data(engine, message, vrt_number)
  File "/Users/user/Documents/test/loader/loader_asyncio.py", line 90, in _get_compound_data
    yield from meta.reflect(bind=engine)
  File "/anaconda/envs/asap/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 3652, in reflect
    with bind.connect() as conn:
AttributeError: 'Engine' object has no attribute 'connect'
Exception ignored in: <bound method Connection.__del__ of <aiomysql.connection.Connection object at 0x1039a8940>>
Traceback (most recent call last):
  File "/anaconda/envs/asap/lib/python3.5/site-packages/aiomysql/connection.py", line 694, in __del__
  File "/anaconda/envs/asap/lib/python3.5/site-packages/aiomysql/connection.py", line 260, in close
  File "/anaconda/envs/asap/lib/python3.5/asyncio/selector_events.py", line 573, in close
  File "/anaconda/envs/asap/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/anaconda/envs/asap/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/anaconda/envs/asap/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed

**Comment by asvetlov** [comment]
Not a chance

**Comment by popravich** [comment]
Explanation is here aio-libs/aiopg#135 / aio-libs/aiopg#115
