### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'affected_rows'

### ISSUE THREAD

**Issue by averrin** [aio-libs/aiomysql#95]
requirements:
```
PyMySQL<=0.6.7
aiomysql
```

code:
```python
async def test(conn):
    async with conn.cursor() as cur:
        q = """SELECT 1;"""
        cur.execute(q)
```

```
Traceback (most recent call last):
  File "main.py", line 129, in test
    cur.execute(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 297, in _query
    self._do_get_result()
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 347, in _do_get_result
    super(DictCursorMixin, self)._do_get_result()
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 306, in _do_get_result
    self.rowcount = result.affected_rows
AttributeError: 'NoneType' object has no attribute 'affected_rows'
```

but it works with bare pymysql

**Comment by asvetlov** [comment]
Something bad with your snippet: you should await `cur.execute(...)` at least.

P.S. The library test suite has tests very close to your code: https://github.com/aio-libs/aiomysql/blob/198fa39fb0346b92835158a1e7a8b11eda0fc114/tests/test_connection.py#L38
It just works.

**Comment by averrin** [comment]
Hi, sorry for long answer.
Here is example with await (last one is a result of many experiments)

```python
async with pool.acquire() as att_conn:
        async with att_conn.cursor() as cur:
            q = templates['select_attendance_vacations'].render()
            await cur.execute(q)
            vacations = await cur.fetchall()
```

and more traceback:
```
Traceback (most recent call last):
  File "main.py", line 223, in updateVacations
    await cur.execute(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 297, in _query
    self._do_get_result()
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 347, in _do_get_result
    super(DictCursorMixin, self)._do_get_result()
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 306, in _do_get_result
    self.rowcount = result.affected_rows
AttributeError: 'NoneType' object has no attribute 'affected_rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 327, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "main.py", line 104, in main
    return await asyncio.gather(task, att_task, initServer())
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 63, in att_periodic
    await updateVacations()
  File "main.py", line 224, in updateVacations
    vacations = await cur.fetchall()
  File "/usr/local/lib/python3.5/site-packages/aiomysql/utils.py", line 67, in __aexit__
    yield from self._obj.close()
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<periodic() running at main.py:58> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(0)() at /usr/local/lib/
python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/local/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
```

**Comment by averrin** [comment]
More info:
1. I use cursorclass=pymysql.cursors.DictCursor
2. this code using aiomysql and aiopg at the same time, including this func:
```python
async def updateVacations():
    async with pools['attendance'].acquire() as att_conn:
        async with att_conn.cursor() as cur:
            q = templates['select_attendance_vacations'].render()
            await cur.execute(q)
            vacations = await cur.fetchall()
    async with pools['sst'].acquire() as conn:
        async with conn.cursor() as scur:
            q = templates['update_vacations'].render({
                "vacations": vacations
            })
            await scur.execute(q)
```

**Comment by jettify** [comment]
@averrin `aiomysql. DictCursor` should be used instead of `pymysql.cursors.DictCursor`.

**Comment by averrin** [comment]
@jettify OMG, thx!!!
